### ISSUE TITLE
Support for the new glpi-agent?

### ISSUE THREAD

**Issue by mathieumd** [ipr-cnrs/fusioninventory#12]
We love your role, thanks for it!

Are you planing to also support the new [glpi-agent](https://github.com/glpi-project/glpi-agent)?

Currently [installation](https://glpi-agent.readthedocs.io/en/latest/installation/index.html) doesn't have stable URIs yet, but it looks like they will provide `.deb` just like they do for FusInv.

So it should consist on simply supporting these (future) URIs, and an option for replacing `fusioninventory-agent` package, if user choose to replace it by `glpi-agent`.

**Comment by gardouille** [comment]
Thanks for your support :)

I didn't knew the existence of glpi-agent before your comment :)

I will keep an eye on the project, but indeed, without a stable release it will be a bit difficult to have something relevant with ansible.
Also it might need extra changes… Config files might diverge from fi-agent overtime, dependencies,…

Please post an update if you see the release of any stable release|url ;)

**Comment by g-bougard** [comment]
Hi @gardouille 
just a quick update, I just published first official release on github: [GLPI-Agent releases](https://github.com/glpi-project/glpi-agent/releases)

**Comment by gardouille** [comment]
glpi-agent role exists from several months :sweat_smile: 
https://github.com/ipr-cnrs/glpi-agent (with molecule tests, better doc,…).

**Comment by g-bougard** [comment]
Hi @gardouille 

just in case you missed it, the repository you linked seems not public.

**Comment by gardouille** [comment]
Fixed ! (wrong URL…) Thank you :sweat_smile:
