### ISSUE TITLE
debian.fusioninventory.org (for deb package) is down

### ISSUE THREAD

**Issue by roumano** [ipr-cnrs/fusioninventory#15]
As the server debian.fusioninventory.org is down
  the role should use github URL to down deb file
 they also change their install procedure in [https://documentation.fusioninventory.org](https://documentation.fusioninventory.org/%20FusionInventory_agent/%20%20%20Installation/linux/deb/) with these new URL

The file `defaults/main.yml` should be updated for the fusioninventory__agent_package_url; with : 
```
fusioninventory__agent_version: '2.5.2-1'
fusioninventory__agent_major_version: '2.5.2'
fusioninventory__agent_package_url: '{{ "https://github.com/fusioninventory/fusioninventory-agent/releases/download/" + fusioninventory__agent_major_version + "/fusioninventory-agent_" + fusioninventory__agent_version + "_all.deb"
```

Need a new variable as on github, deb file are in a directory, so need to be able to sparse it correctly
As example, for 2.6 version variable should be :  
```
fusioninventory__agent_version: '2.6-1'
fusioninventory__agent_major_version: '2.6'
```

**Comment by gardouille** [comment]
Thanks for these informations :)
